version: "3"

services:
  web1:
    image: httpd:2.4
    volumes:
      - /web1:/var/www/html/
    ports:
      - 8001:80 
    container_name: 'app1'  

  web2:
    image: httpd:2.4
    volumes:
      - /web2:/var/www/html/
    ports: 
      - 8002:80
    container_name: 'app2'  

  haproxy:
     image: haproxy:1.7
     volumes: 
       - /haproxy:/usr/local/etc/haproxy/haproxy.cfg:ro
     ports:
      - 8000:80
  
